# Generated by Django 6.0.4 on 2026-04-15 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "mobile_number",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter valid mobile number",
                                regex="^[6-9]\\d{9}$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "password",
                    models.CharField(
                        max_length=128,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                8, message="Password should have at least 8 characters"
                            )
                        ],
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("recruiter", "Recruiter"), ("seeker", "Seeker")],
                        default="seeker",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
