# Generated by Django 6.0.4 on 2026-04-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="role",
            field=models.CharField(
                choices=[("recruiter", "Recruiter")], default="seeker", max_length=20
            ),
        ),
    ]
