# Generated by Django 6.0.4 on 2026-04-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_users_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="role",
            field=models.CharField(default="recruiter", max_length=20),
        ),
    ]
